### ISSUE TITLE
Potential problems with cache control

### ISSUE THREAD

**Issue by must** [CONNECT-platform/connect-platform#18]
API caching will be a really important aspect of the platform as it could lead to better performance when done right and to outright wrong results if done wrong.

Some articles that might help:
[Implementing API cache control](https://docs.fastly.com/guides/api-caching/implementing-api-cache-control)
[How-to: HTTP Caching for RESTful & Hypermedia APIs](https://www.apiacademy.co/articles/2015/12/how-to-http-caching-for-restful-hypermedia-apis)
[RESTful Web Services - Caching](https://www.tutorialspoint.com/restful/restful_caching.htm)

**Comment by loreanvictor** [comment]
yeah since this is a future feature will be closing it for now.
