### ISSUE TITLE
Ability to export/import nodes

### ISSUE THREAD

**Issue by must** [CONNECT-platform/connect-platform#29]
An accessible way of exporting / importing end-point logic would be interesting from multiple perspectives:
- Save logic for sharing with other people (like snippets)
- Shareable test cases
- Easily accessible logic blocks for documentation purposes / Tutorials

I'm pretty sure we can come up with many more use cases for a functionality like this. And I am aware that the logic is already translated into a file format somewhere in the platform. This functionality is about providing an easy way of exporting / importing such a logic.

**Comment by loreanvictor** [comment]
@must I suspect this is related to #13 . could you please reflect your opinion on that thread?
