### ISSUE TITLE
Could a sandbox mode be interesting?

### ISSUE THREAD

**Issue by must** [CONNECT-platform/connect-platform#33]
A sort of debug / sandbox mode would be interesting to test out things without having an impact on the actual logic. This is a random thought that needs to be explored more in depth as we dive into more concrete, real-world applications.

**Comment by loreanvictor** [comment]
@must we have the `test` feature, what is the difference between it and what you are thinking of?

**Comment by must** [comment]
I honestly don't have any idea about how the test feature works. But my thinking as already explained is that you sometimes need "dry-runs" of your code kind of like how you would do it in unit tests / integration tests (the concept of mocking for example but necessary exactly the same).
