### ISSUE TITLE
Streaming Nodes

### ISSUE THREAD

**Issue by loreanvictor** [CONNECT-platform/connect-platform#37]
what about nodes streaming data instead of putting out once? i.e. the node does not stop execution after first output and actually multiple outputs can be outputted? the node obviously would then need to explicitly finish the stream. I don't know, it might be a useful concept specifically as it enables asynchronous iteration (something we currently cannot support). however, it also makes understanding and specifically debugging the code much harder.

@must @CowboyBebug ideas?

**Comment by must** [comment]
Can you elaborate / clarify the idea? At first glance it seems like you're talking about some kind of socket based mechanism but you could also mean a stateful API with a continuously running instance behind the scene. In both cases I can't see the use-fullness of this in the context of web APIs.

What is meant with asynchronous iteration (like can you provide a concrete example of how would that work?)

**Comment by loreanvictor** [comment]
by asynchronous iteration I mean branching off a dynamic number of parallel execution branches.
anyways, closing this one for now. maybe revisit later.
