### ISSUE TITLE
"Install custom code" hides on input click bug

### ISSUE THREAD

**Issue by must** [CONNECT-platform/connect-platform#39]
When you open the Install custom code modal / page and then click on one of the inputs or tab to the other one, it automatically closes. This only happens once (first click) for each of the two inputs.

cc @loreanvictor

**Comment by loreanvictor** [comment]
@must couldn't replicate this.

**Comment by must** [comment]
Video of the bug: https://mustsbucket.s3-eu-central-1.amazonaws.com/Bug.mov

This was tested on Chrome Version 69.0.3497.100 macOS Mojave

**Comment by loreanvictor** [comment]
@must still couldn't replicate. guess this one is on you.

**Comment by must** [comment]
This seems to be resolved in the last version, from what I saw when I tried to reproduce.
