### ISSUE TITLE
Add production configuration support

### ISSUE THREAD

**Issue by must** [CONNECT-platform/connect-platform#50]
Add support for production configuration that only loads on production and is not committed to the repo.

**Comment by loreanvictor** [comment]
committing to [a] repo is a choice outside the scope of the platform as it does not handle version control itself.

**Comment by must** [comment]
The point was about being able to distinguish between production configuration and development configuration or env dependent configuration in this case (it does include what you commit to the repo but also this means having a hidden version of config that is not committed (as in ignored) and which should be initially done by the platform's repo for people who just clone it for example)

**Comment by loreanvictor** [comment]
all of the files generated by the platform are git-ignored in the default boilerplate projects, including the now separate production config alongside the old general config.
