### ISSUE TITLE
Missing package "event-stream" in dependencies. 

### ISSUE THREAD

**Issue by adrianriddle** [CONNECT-platform/connect-platform#56]
When installing on a local machine using npm i:
404 Not Found: event-stream@3.3.6

That version is not available on npm, possibly due to the hack on that library.

**Comment by loreanvictor** [comment]
thanks for the issue. I forgot to update the package-lock file after that fiasco basically. it should be fixed now.

**Comment by loreanvictor** [comment]
closing the issue for now. if the issue persists, feel free to re-open it.

**Comment by loreanvictor** [comment]
yes I believe connect-platform-boilerplate uses the NPM package. should be fixed now.

**Comment by adrianriddle** [comment]
I think you need to update this one too: flatmap-stream@0.1.1

**Comment by loreanvictor** [comment]
no it was a case of not properly updated package-lock.json. should work now. if the issue persists, please open an issue on [connect-platform-boilerplate](https://github.com/CONNECT-platform/connect-platform-boilerplate) project since the issue is related to that one.
