### ISSUE TITLE
Input arrow

### ISSUE THREAD

**Issue by must** [CONNECT-platform/connect-platform#75]
Sometimes when connection an output to an input an additional arrow from the input appears and persists which is far from optimal.
[Check screenshot here](https://www.dropbox.com/s/a8tighqv7jitplr/Screenshot%202019-05-28%2016.23.50.png?dl=0)

**Comment by loreanvictor** [comment]
this should be improved now. but still the issue might persist.
generally, if you wait a long time between your mousedown and mouseup actions, the pin will interpret this as two separate actions. this behavior is not going to change to maintain a smooth flow of creating consecutive arrows, however there is a cooldown time between such events to prevent the scenario described. keep an eye on this, as the cooldown obviously requires fine-tuning. keeping this open for now.

**Comment by loreanvictor** [comment]
seems to be fine now. if the behavior is observed again, please re-open this.
