### ISSUE TITLE
Initialization code / node

### ISSUE THREAD

**Issue by must** [CONNECT-platform/connect-platform#82]
It would be very useful to have a way of running initialization nodes after the configuration has been loaded. Is there a way to do this already or can we implement a simple mechanism to achieve this? This would be useful when it comes to setting up event listeners.

**Comment by loreanvictor** [comment]
that capability is already implemented. you generally would need to subscribe to platform's bind event, which happens after all configs are loaded, initializations are conducted and routes are also established.

for example, you can use this snippet to your initialization script or any custom package's code:

```js
const platform = require('connect-platform');

platform.subscribe(platform.events.bind, () => {
  /** your post-initialization code here **/
});
```

**Comment by must** [comment]
Your suggestion works.
